export const Countries = [
    {
        name: "All",
        emoji: "🌎",
        image: "",
        iso_3166_1: "",
    },
    {
        name: "United States",
        emoji: "🇺🇸",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg",
        iso_3166_1: "US",
    },
    {
        name: "Australia",
        emoji: "🇦🇺",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg",
        iso_3166_1: "AU",
    },
    {
        name: "Brazil",
        emoji: "🇧🇷",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg",
        iso_3166_1: "BR",
    },
    {
        name: "Canada",
        emoji: "🇨🇦",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg",
        iso_3166_1: "CA",
    },
    {
        name: "China",
        emoji: "🇨🇳",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg",
        iso_3166_1: "CN",
    },//
    {
        name: "Colombia",
        emoji: "🇨🇴",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg",
        iso_3166_1: "CO",
    },
    {
        name: "Costa Rica",
        emoji: "🇨🇷",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg",
        iso_3166_1: "CR",
    },
    {
        name: "Cuba",
        emoji: "🇨🇺",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg",
        iso_3166_1: "CU",
    },
    {
        name: "Cyprus",
        emoji: "🇨🇾",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg",
        iso_3166_1: "CY",
    },
    {
        name: "Germany",
        emoji: "🇩🇪",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg",
        iso_3166_1: "DE",
    },
    {
        name: "Denmark",
        emoji: "🇩🇰",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg",
        iso_3166_1: "DK",
    },
    {
        name: "Egypt",
        emoji: "🇪🇬",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg",
        iso_3166_1: "EG",
    },
    {
        name: "Spain",
        emoji: "🇪🇸",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg",
        iso_3166_1: "ES",
    },
    {
        name: "Ethiopia",
        emoji: "🇪🇹",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg",
        iso_3166_1: "ET",
    },
    {
        name: "Finland",
        emoji: "🇫🇮",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg",
        iso_3166_1: "FI",
    },
    {
        name: "France",
        emoji: "🇫🇷",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg",
        iso_3166_1: "FR",
    },
    {
        name: "United Kingdom",
        emoji: "🇬🇧",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg",
        iso_3166_1: "GB",
    },
    {
        name: "Greenland",
        emoji: "🇬🇱",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GL.svg",
        iso_3166_1: "GL",
    },
    {
        name: "Greece",
        emoji: "🇬🇷",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg",
        iso_3166_1: "GR",
    },
    {
        name: "Guatemala",
        emoji: "🇬🇹",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg",
        iso_3166_1: "GT",
    },
    {
        name: "Croatia",
        emoji: "🇭🇷",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg",
        iso_3166_1: "HR",
    },
    {
        name: "Hungary",
        emoji: "🇭🇺",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg",
        iso_3166_1: "HU",
    },
    {
        name: "Indonesia",
        emoji: "🇮🇩",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg",
        iso_3166_1: "ID",
    },
    {
        name: "Ireland",
        emoji: "🇮🇪",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg",
        iso_3166_1: "IE",
    },
    {
        name: "Israel",
        emoji: "🇮🇱",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg",
        iso_3166_1: "IL",
    },
    {
        name: "India",
        emoji: "🇮🇳",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg",
        iso_3166_1: "IN",
    },
    {
        name: "Iceland",
        emoji: "🇮🇸",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg",
        iso_3166_1: "IS",
    },
    {
        name: "Italy",
        emoji: "🇮🇹",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg",
        iso_3166_1: "IT",
    },
    {
        name: "Japan",
        emoji: "🇯🇵",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg",
        iso_3166_1: "JP",
    },
    {
        name: "South Korea",
        emoji: "🇰🇷",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg",
        iso_3166_1: "KR",
    },
    {
        name: "Morocco",
        emoji: "🇲🇦",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg",
        iso_3166_1: "MA",
    },
    {
        name: "Moldova",
        emoji: "🇲🇩",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg",
        iso_3166_1: "MD",
    },
    {
        name: "Madagascar",
        emoji: "🇲🇬",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg",
        iso_3166_1: "MG",
    },
    {
        name: "Mongolia",
        emoji: "🇲🇳",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg",
        iso_3166_1: "MN",
    },
    {
        name: "Mexico",
        emoji: "🇲🇽",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg",
        iso_3166_1: "MX",
    },
    {
        name: "Malaysia",
        emoji: "🇲🇾",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg",
        iso_3166_1: "MY",
    },
    {
        name: "Nigeria",
        emoji: "🇳🇬",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg",
        iso_3166_1: "NG",
    },
    {
        name: "Nicaragua",
        emoji: "🇳🇮",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg",
        iso_3166_1: "NI",
    },
    {
        name: "Netherlands",
        emoji: "🇳🇱",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg",
        iso_3166_1: "NL",
    },
    {
        name: "Norway",
        emoji: "🇳🇴",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg",
        iso_3166_1: "NO",
    },
    {
        name: "Nepal",
        emoji: "🇳🇵",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg",
        iso_3166_1: " NP",
    },
    {
        name: "New Zealand",
        emoji: "🇳🇿",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg",
        iso_3166_1: "NZ",
    },
    {
        name: "Peru",
        emoji: "🇵🇪",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg",
        iso_3166_1: "PE",
    },
    {
        name: "Philippines",
        emoji: "🇵🇭",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg",
        iso_3166_1: "PH",
    },
    {
        name: "Poland",
        emoji: "🇵🇱",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg",
        iso_3166_1: "PL",
    },
    {
        name: "Portugal",
        emoji: "🇵🇹",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg",
        iso_3166_1: "PT",
    },
    {
        name: "Qatar",
        emoji: "🇶🇦",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg",
        iso_3166_1: "QA",
    },
    {
        name: "Romania",
        emoji: "🇷🇴",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg",
        iso_3166_1: "RO",
    },
    {
        name: "Serbia",
        emoji: "🇷🇸",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg",
        iso_3166_1: "RS",
    },
    {
        name: "Russia",
        emoji: "🇷🇺",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg",
        iso_3166_1: "RU",
    },
    {
        name: "Sweden",
        emoji: "🇸🇪",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg",
        iso_3166_1: "SE",
    },
    {
        name: "Singapore",
        emoji: "🇸🇬",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg",
        iso_3166_1: "SG",
    },
    {
        name: "Slovenia",
        emoji: "🇸🇮",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg",
        iso_3166_1: "SI",
    },
    {
        name: "Slovakia",
        emoji: "🇸🇰",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg",
        iso_3166_1: "SK",
    },
    {
        name: "Thailand",
        emoji: "🇹🇭",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg",
        iso_3166_1: "TH",
    },
    {
        name: "Turkey",
        emoji: "🇹🇷",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg",
        iso_3166_1: "TR",
    },
    {
        name: "Taiwan",
        emoji: "🇹🇼",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg",
        iso_3166_1: "TW",
    },
    {
        name: "Ukraine",
        emoji: "🇺🇦",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg",
        iso_3166_1: "UA",
    },
    {
        name: "Venezuela",
        emoji: "🇻🇪",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg",
        iso_3166_1: "VE",
    },
    {
        name: "Vietnam",
        emoji: "🇻🇳",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg",
        iso_3166_1: "VN",
    },
    {
        name: "South Africa",
        emoji: "🇿🇦",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg",
        iso_3166_1: "ZA",
    },
    {
        name: "Zambia",
        emoji: "🇿🇲",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg",
        iso_3166_1: "ZM",
    },
    {
        name: "Zimbabwe",
        emoji: "🇿🇼",
        image: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg",
        iso_3166_1: "ZW",
    },
];
//TODO: what is this?
// {
//     "name": "England",
//     "emoji": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
//     "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ENGLAND.svg",
//     "iso_3166_1": ""
// },
// {
//     "name": "Scotland",
//     "emoji": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
//     "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SCOTLAND.svg",
//     "iso_3166_1": ""
// }
