import { Movie } from "./types/movie";

export const MOCK_MOVIES: Movie[] = [
    {
        actors: "Frank Welker, Mindy Cohn, Matthew Lillard, Grey Griffin",
        adult: false,
        backdrop_path: "/oVROUaJkzEBAlNbUKnXQiiKbJRf.jpg",
        director: "Ethan Spaulding",
        genre_ids: [16, 35, 10751, 9648],
        id: "45752",
        imdbID: "tt1731767",
        imdbRating: "7.3",
        imdbVotes: "2,665",
        poster_path:
            "https://m.media-amazon.com/images/M/MV5BZTYyYjg3MDEtNmQ0My00YTA5LWIyNGUtZmQ0NTY2NjA1ZWJhXkEyXkFqcGdeQXVyNDQ5MDYzMTk@._V1_SX300.jpg",
        release_date: "2010-09-14",
        title: "Scooby-Doo! Camp Scare",
        video: "",
        website: "N/A",
    },
    {
        actors: "Charlize Theron, James McAvoy, John Goodman",
        adult: false,
        backdrop_path: "/g3hni0i9iAQ13jDGOFWavJFlojc.jpg",
        director: "David Leitch",
        genre_ids: [28, 53],
        id: "341013",
        imdbID: "tt2406566",
        imdbRating: "6.7",
        imdbVotes: "204,324",
        poster_path:
            "https://m.media-amazon.com/images/M/MV5BMjM5NDYzMzg5N15BMl5BanBnXkFtZTgwOTM2NDU1MjI@._V1_SX300.jpg",
        release_date: "2017-07-26",
        title: "Atomic Blonde",
        video: "",
        website: "N/A",
    },
    {
        actors: "Diana Kaarina, Adrian Petriw, Britt Irvin, Cassandra Lee Morris",
        adult: false,
        backdrop_path: "/4yN3l7ZQgGDZOewvoiWKcLt7EVb.jpg",
        director: "William Lau",
        genre_ids: [16, 10751, 14],
        id: "57737",
        imdbID: "tt1800254",
        imdbRating: "5.8",
        imdbVotes: "1,487",
        poster_path:
            "https://m.media-amazon.com/images/M/MV5BOTU2Yzk1OWYtNDRmNy00MWM1LTkwNDEtMzU3ZGQzMWQ5NTZiXkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_SX300.jpg",
        release_date: "2011-03-01",
        title: "Barbie: A Fairy Secret",
        video: "",
        website: "N/A",
    },
    {
        actors: "Colin Farrell, Scott Caan, Ali Larter",
        adult: false,
        backdrop_path: "/6TkIKjHz4UYu2Z1I7tF57Frcz7i.jpg",
        director: "Les Mayfield",
        genre_ids: [37, 28],
        id: "13496",
        imdbID: "tt0244000",
        imdbRating: "5.9",
        imdbVotes: "17,251",
        poster_path:
            "https://m.media-amazon.com/images/M/MV5BMTIwMTYxODAzMV5BMl5BanBnXkFtZTYwNTM3Nzc5._V1_SX300.jpg",
        release_date: "2001-08-17",
        title: "American Outlaws",
        video: "",
        website: "N/A",
    },
];
