import { Avatar } from "../types/player";
import {
    AVATAR_BLUR_IMG_1,
    AVATAR_BLUR_IMG_10,
    AVATAR_BLUR_IMG_2,
    AVATAR_BLUR_IMG_3,
    AVATAR_BLUR_IMG_4,
    AVATAR_BLUR_IMG_5,
    AVATAR_BLUR_IMG_6,
    AVATAR_BLUR_IMG_7,
    AVATAR_BLUR_IMG_8,
    AVATAR_BLUR_IMG_9,
    AVATAR_IMG_1,
    AVATAR_IMG_10,
    AVATAR_IMG_2,
    AVATAR_IMG_3,
    AVATAR_IMG_4,
    AVATAR_IMG_5,
    AVATAR_IMG_6,
    AVATAR_IMG_7,
    AVATAR_IMG_8,
    AVATAR_IMG_9,
} from "../constant/img";

export const Avatars: Avatar[] = [
    { img: AVATAR_IMG_1, hash: AVATAR_BLUR_IMG_1 },
    { img: AVATAR_IMG_2, hash: AVATAR_BLUR_IMG_2 },
    { img: AVATAR_IMG_3, hash: AVATAR_BLUR_IMG_3 },
    { img: AVATAR_IMG_4, hash: AVATAR_BLUR_IMG_4 },
    { img: AVATAR_IMG_5, hash: AVATAR_BLUR_IMG_5 },
    { img: AVATAR_IMG_6, hash: AVATAR_BLUR_IMG_6 },
    { img: AVATAR_IMG_7, hash: AVATAR_BLUR_IMG_7 },
    { img: AVATAR_IMG_8, hash: AVATAR_BLUR_IMG_8 },
    { img: AVATAR_IMG_9, hash: AVATAR_BLUR_IMG_9 },
    { img: AVATAR_IMG_10, hash: AVATAR_BLUR_IMG_10 },
];
